/** @format */

const users = [
  {
    id: 0,
    name: "Felippe Portela",
    roles: [4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 1,
    name: "Gelado",
    roles: [0, 1, 2, 3, 4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 5,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 2,
    name: "Junior Pavão",
    roles: [0, 1, 3],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 3,
    name: "Falcão",
    roles: [6, 5],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 4,
    name: "Nicole",
    roles: [0, 1, 4, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 5,
    name: "Paulo",
    roles: [2, 6, 4, 5],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 6,
    name: "Ray",
    roles: [0, 3, 1],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 7,
    name: "Vitor",
    roles: [0, 1, 2, 3, 4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 5,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 8,
    name: "Thalles",
    roles: [6, 5],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 9,
    name: "Nathalia",
    roles: [4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [],
  },
  {
    id: 10,
    name: "Julia",
    roles: [4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 11,
    name: "Álvaro",
    roles: [4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 12,
    name: "Josemar",
    roles: [4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 13,
    name: "Efrain Sena",
    roles: [4, 5, 6],
    branch_id: 0,
    team_id: 0,
    max_sequential: 1,
    exclude_me_on_days_that_are: [1, 2, 3, 4, 5, 6],
  },
];

export default () => {
  return {
    getUsers: async function () {
      return users;
    },
  };
};
